"""Add refresh_tokens table

Revision ID: 4d4298a09d7e
Revises: 20260215_0003
Create Date: 2026-02-19 11:58:42.284627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4298a09d7e'
down_revision: Union[str, None] = '20260215_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ux_businesses_owner_user_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_owner_user_id'), table_name='businesses')
    op.create_index(op.f('ix_businesses_owner_user_id'), 'businesses', ['owner_user_id'], unique=True)
    op.create_index(op.f('ix_product_variants_business_id'), 'product_variants', ['business_id'], unique=False)
    op.create_index(op.f('ix_sales_parent_sale_id'), 'sales', ['parent_sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_parent_sale_id'), table_name='sales')
    op.drop_index(op.f('ix_product_variants_business_id'), table_name='product_variants')
    op.drop_index(op.f('ix_businesses_owner_user_id'), table_name='businesses')
    op.create_index(op.f('ix_businesses_owner_user_id'), 'businesses', ['owner_user_id'], unique=False)
    op.create_index(op.f('ux_businesses_owner_user_id'), 'businesses', ['owner_user_id'], unique=True)
    # ### end Alembic commands ###
